//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.14 at 06:38:41 PM IST 
//


package com.dc.evans.schema.mercurygate;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MoveType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VesselName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="VoyageNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LLoydsCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}LetterOfCredit"/&gt;
 *         &lt;element name="ImmediateTransportationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImmediateTransportationDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TransportationAndExportationNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImmediateExportNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ExporterReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ExporterLicenseNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ExportLicenseDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FMCNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InternalTransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ElectronicExportInformation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ExportDeclaration" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="USAMSNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="DestinationControlStatement" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ISFShipmentType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ISFBondHolder" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ISFBondNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SuretyNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="PointOfOrigin" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element name="ContainerStuffingLocation" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element name="ContainerStufferLocation" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element name="PortOfEntry" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element name="PortOfExport" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element name="FirstPortOfUnlading" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element name="FinalPortOfDestination" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element name="FinalCountryOfDestination" type="{urn:MercuryGate:import}TypeLocationEnvelope"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}GenericField"/&gt;
 *         &lt;element name="AESVesselFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AESImportEntryNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AESInbondType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AESRelatedCompanies" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AESRoutedTransaction" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReasonForExport" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ECCN" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BlanketPeriodBeginDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="BlanketPeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IsDECPreviligeAvailable" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AesCarrierCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ActionCode1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ActionCode2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="USPPIIrsNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="USPPIIrsIdType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UsStateOfOriginCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AESModeOfTransport" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AESFilingOption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DepartureDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AESForeignTradeZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IncoTerms" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ImportExport" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselIMO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VesselID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="VoyageService" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "moveType",
    "vesselName",
    "voyageNumber",
    "lLoydsCode",
    "letterOfCredit",
    "immediateTransportationNumber",
    "immediateTransportationDate",
    "transportationAndExportationNumber",
    "immediateExportNumber",
    "exporterReferenceNumber",
    "exporterLicenseNumber",
    "exportLicenseDate",
    "fmcNumber",
    "internalTransactionNumber",
    "electronicExportInformation",
    "exportDeclaration",
    "usamsNumber",
    "destinationControlStatement",
    "isfShipmentType",
    "isfBondHolder",
    "isfBondNumber",
    "suretyNumber",
    "pointOfOrigin",
    "containerStuffingLocation",
    "containerStufferLocation",
    "portOfEntry",
    "portOfExport",
    "firstPortOfUnlading",
    "finalPortOfDestination",
    "finalCountryOfDestination",
    "genericField",
    "aesVesselFlag",
    "aesImportEntryNumber",
    "aesInbondType",
    "aesRelatedCompanies",
    "aesRoutedTransaction",
    "reasonForExport",
    "eccn",
    "blanketPeriodBeginDate",
    "blanketPeriodEndDate",
    "isDECPreviligeAvailable",
    "aesCarrierCode",
    "actionCode1",
    "actionCode2",
    "usppiIrsNumber",
    "usppiIrsIdType",
    "usStateOfOriginCode",
    "aesModeOfTransport",
    "aesFilingOption",
    "departureDate",
    "aesForeignTradeZone",
    "incoTerms",
    "importExport",
    "vesselIMO",
    "vesselID",
    "voyageService"
})
@XmlRootElement(name = "InternationalDetails")
public class InternationalDetails {

    @XmlElement(name = "MoveType", required = true)
    protected String moveType;
    @XmlElement(name = "VesselName", required = true)
    protected String vesselName;
    @XmlElement(name = "VoyageNumber", required = true)
    protected String voyageNumber;
    @XmlElement(name = "LLoydsCode", required = true)
    protected String lLoydsCode;
    @XmlElement(name = "LetterOfCredit", required = true)
    protected LetterOfCredit letterOfCredit;
    @XmlElement(name = "ImmediateTransportationNumber", required = true)
    protected String immediateTransportationNumber;
    @XmlElement(name = "ImmediateTransportationDate", required = true)
    protected String immediateTransportationDate;
    @XmlElement(name = "TransportationAndExportationNumber", required = true)
    protected String transportationAndExportationNumber;
    @XmlElement(name = "ImmediateExportNumber", required = true)
    protected String immediateExportNumber;
    @XmlElement(name = "ExporterReferenceNumber", required = true)
    protected String exporterReferenceNumber;
    @XmlElement(name = "ExporterLicenseNumber", required = true)
    protected String exporterLicenseNumber;
    @XmlElement(name = "ExportLicenseDate", required = true)
    protected String exportLicenseDate;
    @XmlElement(name = "FMCNumber", required = true)
    protected String fmcNumber;
    @XmlElement(name = "InternalTransactionNumber", required = true)
    protected String internalTransactionNumber;
    @XmlElement(name = "ElectronicExportInformation", required = true)
    protected String electronicExportInformation;
    @XmlElement(name = "ExportDeclaration", required = true)
    protected String exportDeclaration;
    @XmlElement(name = "USAMSNumber", required = true)
    protected String usamsNumber;
    @XmlElement(name = "DestinationControlStatement", required = true)
    protected String destinationControlStatement;
    @XmlElement(name = "ISFShipmentType", required = true)
    protected String isfShipmentType;
    @XmlElement(name = "ISFBondHolder", required = true)
    protected String isfBondHolder;
    @XmlElement(name = "ISFBondNumber", required = true)
    protected String isfBondNumber;
    @XmlElement(name = "SuretyNumber", required = true)
    protected String suretyNumber;
    @XmlElement(name = "PointOfOrigin", required = true)
    protected TypeLocationEnvelope pointOfOrigin;
    @XmlElement(name = "ContainerStuffingLocation", required = true)
    protected TypeLocationEnvelope containerStuffingLocation;
    @XmlElement(name = "ContainerStufferLocation", required = true)
    protected TypeLocationEnvelope containerStufferLocation;
    @XmlElement(name = "PortOfEntry", required = true)
    protected TypeLocationEnvelope portOfEntry;
    @XmlElement(name = "PortOfExport", required = true)
    protected TypeLocationEnvelope portOfExport;
    @XmlElement(name = "FirstPortOfUnlading", required = true)
    protected TypeLocationEnvelope firstPortOfUnlading;
    @XmlElement(name = "FinalPortOfDestination", required = true)
    protected TypeLocationEnvelope finalPortOfDestination;
    @XmlElement(name = "FinalCountryOfDestination", required = true)
    protected TypeLocationEnvelope finalCountryOfDestination;
    @XmlElement(name = "GenericField", required = true)
    protected GenericField genericField;
    @XmlElement(name = "AESVesselFlag", required = true)
    protected String aesVesselFlag;
    @XmlElement(name = "AESImportEntryNumber", required = true)
    protected String aesImportEntryNumber;
    @XmlElement(name = "AESInbondType", required = true)
    protected String aesInbondType;
    @XmlElement(name = "AESRelatedCompanies", required = true)
    protected String aesRelatedCompanies;
    @XmlElement(name = "AESRoutedTransaction", required = true)
    protected String aesRoutedTransaction;
    @XmlElement(name = "ReasonForExport", required = true)
    protected String reasonForExport;
    @XmlElement(name = "ECCN", required = true)
    protected String eccn;
    @XmlElement(name = "BlanketPeriodBeginDate", required = true)
    protected String blanketPeriodBeginDate;
    @XmlElement(name = "BlanketPeriodEndDate", required = true)
    protected String blanketPeriodEndDate;
    @XmlElement(name = "IsDECPreviligeAvailable")
    protected String isDECPreviligeAvailable;
    @XmlElement(name = "AesCarrierCode")
    protected String aesCarrierCode;
    @XmlElement(name = "ActionCode1")
    protected String actionCode1;
    @XmlElement(name = "ActionCode2")
    protected String actionCode2;
    @XmlElement(name = "USPPIIrsNumber")
    protected String usppiIrsNumber;
    @XmlElement(name = "USPPIIrsIdType")
    protected String usppiIrsIdType;
    @XmlElement(name = "UsStateOfOriginCode")
    protected String usStateOfOriginCode;
    @XmlElement(name = "AESModeOfTransport")
    protected String aesModeOfTransport;
    @XmlElement(name = "AESFilingOption")
    protected String aesFilingOption;
    @XmlElement(name = "DepartureDate")
    protected String departureDate;
    @XmlElement(name = "AESForeignTradeZone")
    protected String aesForeignTradeZone;
    @XmlElement(name = "IncoTerms")
    protected String incoTerms;
    @XmlElement(name = "ImportExport")
    protected String importExport;
    @XmlElement(name = "VesselIMO")
    protected String vesselIMO;
    @XmlElement(name = "VesselID")
    protected String vesselID;
    @XmlElement(name = "VoyageService")
    protected String voyageService;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the moveType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoveType() {
        return moveType;
    }

    /**
     * Sets the value of the moveType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoveType(String value) {
        this.moveType = value;
    }

    /**
     * Gets the value of the vesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselName() {
        return vesselName;
    }

    /**
     * Sets the value of the vesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselName(String value) {
        this.vesselName = value;
    }

    /**
     * Gets the value of the voyageNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoyageNumber() {
        return voyageNumber;
    }

    /**
     * Sets the value of the voyageNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoyageNumber(String value) {
        this.voyageNumber = value;
    }

    /**
     * Gets the value of the lLoydsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLLoydsCode() {
        return lLoydsCode;
    }

    /**
     * Sets the value of the lLoydsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLLoydsCode(String value) {
        this.lLoydsCode = value;
    }

    /**
     * Gets the value of the letterOfCredit property.
     * 
     * @return
     *     possible object is
     *     {@link LetterOfCredit }
     *     
     */
    public LetterOfCredit getLetterOfCredit() {
        return letterOfCredit;
    }

    /**
     * Sets the value of the letterOfCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link LetterOfCredit }
     *     
     */
    public void setLetterOfCredit(LetterOfCredit value) {
        this.letterOfCredit = value;
    }

    /**
     * Gets the value of the immediateTransportationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImmediateTransportationNumber() {
        return immediateTransportationNumber;
    }

    /**
     * Sets the value of the immediateTransportationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImmediateTransportationNumber(String value) {
        this.immediateTransportationNumber = value;
    }

    /**
     * Gets the value of the immediateTransportationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImmediateTransportationDate() {
        return immediateTransportationDate;
    }

    /**
     * Sets the value of the immediateTransportationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImmediateTransportationDate(String value) {
        this.immediateTransportationDate = value;
    }

    /**
     * Gets the value of the transportationAndExportationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransportationAndExportationNumber() {
        return transportationAndExportationNumber;
    }

    /**
     * Sets the value of the transportationAndExportationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportationAndExportationNumber(String value) {
        this.transportationAndExportationNumber = value;
    }

    /**
     * Gets the value of the immediateExportNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImmediateExportNumber() {
        return immediateExportNumber;
    }

    /**
     * Sets the value of the immediateExportNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImmediateExportNumber(String value) {
        this.immediateExportNumber = value;
    }

    /**
     * Gets the value of the exporterReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterReferenceNumber() {
        return exporterReferenceNumber;
    }

    /**
     * Sets the value of the exporterReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterReferenceNumber(String value) {
        this.exporterReferenceNumber = value;
    }

    /**
     * Gets the value of the exporterLicenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExporterLicenseNumber() {
        return exporterLicenseNumber;
    }

    /**
     * Sets the value of the exporterLicenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExporterLicenseNumber(String value) {
        this.exporterLicenseNumber = value;
    }

    /**
     * Gets the value of the exportLicenseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportLicenseDate() {
        return exportLicenseDate;
    }

    /**
     * Sets the value of the exportLicenseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportLicenseDate(String value) {
        this.exportLicenseDate = value;
    }

    /**
     * Gets the value of the fmcNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFMCNumber() {
        return fmcNumber;
    }

    /**
     * Sets the value of the fmcNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFMCNumber(String value) {
        this.fmcNumber = value;
    }

    /**
     * Gets the value of the internalTransactionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternalTransactionNumber() {
        return internalTransactionNumber;
    }

    /**
     * Sets the value of the internalTransactionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternalTransactionNumber(String value) {
        this.internalTransactionNumber = value;
    }

    /**
     * Gets the value of the electronicExportInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElectronicExportInformation() {
        return electronicExportInformation;
    }

    /**
     * Sets the value of the electronicExportInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElectronicExportInformation(String value) {
        this.electronicExportInformation = value;
    }

    /**
     * Gets the value of the exportDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportDeclaration() {
        return exportDeclaration;
    }

    /**
     * Sets the value of the exportDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportDeclaration(String value) {
        this.exportDeclaration = value;
    }

    /**
     * Gets the value of the usamsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSAMSNumber() {
        return usamsNumber;
    }

    /**
     * Sets the value of the usamsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSAMSNumber(String value) {
        this.usamsNumber = value;
    }

    /**
     * Gets the value of the destinationControlStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestinationControlStatement() {
        return destinationControlStatement;
    }

    /**
     * Sets the value of the destinationControlStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestinationControlStatement(String value) {
        this.destinationControlStatement = value;
    }

    /**
     * Gets the value of the isfShipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISFShipmentType() {
        return isfShipmentType;
    }

    /**
     * Sets the value of the isfShipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISFShipmentType(String value) {
        this.isfShipmentType = value;
    }

    /**
     * Gets the value of the isfBondHolder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISFBondHolder() {
        return isfBondHolder;
    }

    /**
     * Sets the value of the isfBondHolder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISFBondHolder(String value) {
        this.isfBondHolder = value;
    }

    /**
     * Gets the value of the isfBondNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISFBondNumber() {
        return isfBondNumber;
    }

    /**
     * Sets the value of the isfBondNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISFBondNumber(String value) {
        this.isfBondNumber = value;
    }

    /**
     * Gets the value of the suretyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuretyNumber() {
        return suretyNumber;
    }

    /**
     * Sets the value of the suretyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuretyNumber(String value) {
        this.suretyNumber = value;
    }

    /**
     * Gets the value of the pointOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getPointOfOrigin() {
        return pointOfOrigin;
    }

    /**
     * Sets the value of the pointOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setPointOfOrigin(TypeLocationEnvelope value) {
        this.pointOfOrigin = value;
    }

    /**
     * Gets the value of the containerStuffingLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getContainerStuffingLocation() {
        return containerStuffingLocation;
    }

    /**
     * Sets the value of the containerStuffingLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setContainerStuffingLocation(TypeLocationEnvelope value) {
        this.containerStuffingLocation = value;
    }

    /**
     * Gets the value of the containerStufferLocation property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getContainerStufferLocation() {
        return containerStufferLocation;
    }

    /**
     * Sets the value of the containerStufferLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setContainerStufferLocation(TypeLocationEnvelope value) {
        this.containerStufferLocation = value;
    }

    /**
     * Gets the value of the portOfEntry property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getPortOfEntry() {
        return portOfEntry;
    }

    /**
     * Sets the value of the portOfEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setPortOfEntry(TypeLocationEnvelope value) {
        this.portOfEntry = value;
    }

    /**
     * Gets the value of the portOfExport property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getPortOfExport() {
        return portOfExport;
    }

    /**
     * Sets the value of the portOfExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setPortOfExport(TypeLocationEnvelope value) {
        this.portOfExport = value;
    }

    /**
     * Gets the value of the firstPortOfUnlading property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getFirstPortOfUnlading() {
        return firstPortOfUnlading;
    }

    /**
     * Sets the value of the firstPortOfUnlading property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setFirstPortOfUnlading(TypeLocationEnvelope value) {
        this.firstPortOfUnlading = value;
    }

    /**
     * Gets the value of the finalPortOfDestination property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getFinalPortOfDestination() {
        return finalPortOfDestination;
    }

    /**
     * Sets the value of the finalPortOfDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setFinalPortOfDestination(TypeLocationEnvelope value) {
        this.finalPortOfDestination = value;
    }

    /**
     * Gets the value of the finalCountryOfDestination property.
     * 
     * @return
     *     possible object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public TypeLocationEnvelope getFinalCountryOfDestination() {
        return finalCountryOfDestination;
    }

    /**
     * Sets the value of the finalCountryOfDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeLocationEnvelope }
     *     
     */
    public void setFinalCountryOfDestination(TypeLocationEnvelope value) {
        this.finalCountryOfDestination = value;
    }

    /**
     * Gets the value of the genericField property.
     * 
     * @return
     *     possible object is
     *     {@link GenericField }
     *     
     */
    public GenericField getGenericField() {
        return genericField;
    }

    /**
     * Sets the value of the genericField property.
     * 
     * @param value
     *     allowed object is
     *     {@link GenericField }
     *     
     */
    public void setGenericField(GenericField value) {
        this.genericField = value;
    }

    /**
     * Gets the value of the aesVesselFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESVesselFlag() {
        return aesVesselFlag;
    }

    /**
     * Sets the value of the aesVesselFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESVesselFlag(String value) {
        this.aesVesselFlag = value;
    }

    /**
     * Gets the value of the aesImportEntryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESImportEntryNumber() {
        return aesImportEntryNumber;
    }

    /**
     * Sets the value of the aesImportEntryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESImportEntryNumber(String value) {
        this.aesImportEntryNumber = value;
    }

    /**
     * Gets the value of the aesInbondType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESInbondType() {
        return aesInbondType;
    }

    /**
     * Sets the value of the aesInbondType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESInbondType(String value) {
        this.aesInbondType = value;
    }

    /**
     * Gets the value of the aesRelatedCompanies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESRelatedCompanies() {
        return aesRelatedCompanies;
    }

    /**
     * Sets the value of the aesRelatedCompanies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESRelatedCompanies(String value) {
        this.aesRelatedCompanies = value;
    }

    /**
     * Gets the value of the aesRoutedTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESRoutedTransaction() {
        return aesRoutedTransaction;
    }

    /**
     * Sets the value of the aesRoutedTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESRoutedTransaction(String value) {
        this.aesRoutedTransaction = value;
    }

    /**
     * Gets the value of the reasonForExport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonForExport() {
        return reasonForExport;
    }

    /**
     * Sets the value of the reasonForExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonForExport(String value) {
        this.reasonForExport = value;
    }

    /**
     * Gets the value of the eccn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECCN() {
        return eccn;
    }

    /**
     * Sets the value of the eccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECCN(String value) {
        this.eccn = value;
    }

    /**
     * Gets the value of the blanketPeriodBeginDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlanketPeriodBeginDate() {
        return blanketPeriodBeginDate;
    }

    /**
     * Sets the value of the blanketPeriodBeginDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlanketPeriodBeginDate(String value) {
        this.blanketPeriodBeginDate = value;
    }

    /**
     * Gets the value of the blanketPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlanketPeriodEndDate() {
        return blanketPeriodEndDate;
    }

    /**
     * Sets the value of the blanketPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlanketPeriodEndDate(String value) {
        this.blanketPeriodEndDate = value;
    }

    /**
     * Gets the value of the isDECPreviligeAvailable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDECPreviligeAvailable() {
        return isDECPreviligeAvailable;
    }

    /**
     * Sets the value of the isDECPreviligeAvailable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDECPreviligeAvailable(String value) {
        this.isDECPreviligeAvailable = value;
    }

    /**
     * Gets the value of the aesCarrierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAesCarrierCode() {
        return aesCarrierCode;
    }

    /**
     * Sets the value of the aesCarrierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAesCarrierCode(String value) {
        this.aesCarrierCode = value;
    }

    /**
     * Gets the value of the actionCode1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionCode1() {
        return actionCode1;
    }

    /**
     * Sets the value of the actionCode1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionCode1(String value) {
        this.actionCode1 = value;
    }

    /**
     * Gets the value of the actionCode2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionCode2() {
        return actionCode2;
    }

    /**
     * Sets the value of the actionCode2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionCode2(String value) {
        this.actionCode2 = value;
    }

    /**
     * Gets the value of the usppiIrsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPPIIrsNumber() {
        return usppiIrsNumber;
    }

    /**
     * Sets the value of the usppiIrsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPPIIrsNumber(String value) {
        this.usppiIrsNumber = value;
    }

    /**
     * Gets the value of the usppiIrsIdType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSPPIIrsIdType() {
        return usppiIrsIdType;
    }

    /**
     * Sets the value of the usppiIrsIdType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSPPIIrsIdType(String value) {
        this.usppiIrsIdType = value;
    }

    /**
     * Gets the value of the usStateOfOriginCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsStateOfOriginCode() {
        return usStateOfOriginCode;
    }

    /**
     * Sets the value of the usStateOfOriginCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsStateOfOriginCode(String value) {
        this.usStateOfOriginCode = value;
    }

    /**
     * Gets the value of the aesModeOfTransport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESModeOfTransport() {
        return aesModeOfTransport;
    }

    /**
     * Sets the value of the aesModeOfTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESModeOfTransport(String value) {
        this.aesModeOfTransport = value;
    }

    /**
     * Gets the value of the aesFilingOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESFilingOption() {
        return aesFilingOption;
    }

    /**
     * Sets the value of the aesFilingOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESFilingOption(String value) {
        this.aesFilingOption = value;
    }

    /**
     * Gets the value of the departureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureDate() {
        return departureDate;
    }

    /**
     * Sets the value of the departureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureDate(String value) {
        this.departureDate = value;
    }

    /**
     * Gets the value of the aesForeignTradeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAESForeignTradeZone() {
        return aesForeignTradeZone;
    }

    /**
     * Sets the value of the aesForeignTradeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAESForeignTradeZone(String value) {
        this.aesForeignTradeZone = value;
    }

    /**
     * Gets the value of the incoTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncoTerms() {
        return incoTerms;
    }

    /**
     * Sets the value of the incoTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncoTerms(String value) {
        this.incoTerms = value;
    }

    /**
     * Gets the value of the importExport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportExport() {
        return importExport;
    }

    /**
     * Sets the value of the importExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportExport(String value) {
        this.importExport = value;
    }

    /**
     * Gets the value of the vesselIMO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselIMO() {
        return vesselIMO;
    }

    /**
     * Sets the value of the vesselIMO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselIMO(String value) {
        this.vesselIMO = value;
    }

    /**
     * Gets the value of the vesselID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselID() {
        return vesselID;
    }

    /**
     * Sets the value of the vesselID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselID(String value) {
        this.vesselID = value;
    }

    /**
     * Gets the value of the voyageService property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoyageService() {
        return voyageService;
    }

    /**
     * Sets the value of the voyageService property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoyageService(String value) {
        this.voyageService = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
