//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.14 at 06:38:41 PM IST 
//


package com.dc.evans.schema.mercurygate;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ReferenceNumbers" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}MonetaryValue" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ContainedBy" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}LineItem"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Dimensions" minOccurs="0"/&gt;
 *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}FreightClasses" minOccurs="0"/&gt;
 *         &lt;element name="Commodity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NmfcCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="StccCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Stackability" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="TrackingNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="DeliveryStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MinTemperature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MaxTemperature" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TemperatureUnits" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="HazardousMaterial" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}HazMatDetail" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Weights"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Quantities"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="isShipUnit" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="isHandlingUnit" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "ItemGroup")
public class ItemGroup {

    @XmlElement(name = "ReferenceNumbers")
    protected ReferenceNumbers referenceNumbers;
    @XmlElement(name = "MonetaryValue")
    protected MonetaryValue monetaryValue;
    @XmlElement(name = "ContainedBy")
    protected ContainedBy containedBy;
    @XmlElement(name = "LineItem", required = true)
    protected LineItem lineItem;
    @XmlElement(name = "Dimensions")
    protected Dimensions dimensions;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "FreightClasses")
    protected FreightClasses freightClasses;
    @XmlElement(name = "Commodity")
    protected String commodity;
    @XmlElement(name = "NmfcCode")
    protected String nmfcCode;
    @XmlElement(name = "StccCode")
    protected String stccCode;
    @XmlElement(name = "Stackability")
    protected BigInteger stackability;
    @XmlElement(name = "TrackingNumber")
    protected String trackingNumber;
    @XmlElement(name = "DeliveryStatus")
    protected String deliveryStatus;
    @XmlElement(name = "MinTemperature")
    protected String minTemperature;
    @XmlElement(name = "MaxTemperature")
    protected String maxTemperature;
    @XmlElement(name = "TemperatureUnits")
    protected String temperatureUnits;
    @XmlElement(name = "HazardousMaterial")
    protected String hazardousMaterial;
    @XmlElement(name = "HazMatDetail")
    protected HazMatDetail hazMatDetail;
    @XmlElement(name = "Weights", required = true)
    protected Weights weights;
    @XmlElement(name = "Quantities", required = true)
    protected Quantities quantities;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "isShipUnit")
    protected Boolean isShipUnit;
    @XmlAttribute(name = "isHandlingUnit")
    protected Boolean isHandlingUnit;
    @XmlAttribute(name = "sequence")
    protected String sequence;

    /**
     * Gets the value of the referenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumbers }
     *     
     */
    public ReferenceNumbers getReferenceNumbers() {
        return referenceNumbers;
    }

    /**
     * Sets the value of the referenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumbers }
     *     
     */
    public void setReferenceNumbers(ReferenceNumbers value) {
        this.referenceNumbers = value;
    }

    /**
     * Gets the value of the monetaryValue property.
     * 
     * @return
     *     possible object is
     *     {@link MonetaryValue }
     *     
     */
    public MonetaryValue getMonetaryValue() {
        return monetaryValue;
    }

    /**
     * Sets the value of the monetaryValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonetaryValue }
     *     
     */
    public void setMonetaryValue(MonetaryValue value) {
        this.monetaryValue = value;
    }

    /**
     * Gets the value of the containedBy property.
     * 
     * @return
     *     possible object is
     *     {@link ContainedBy }
     *     
     */
    public ContainedBy getContainedBy() {
        return containedBy;
    }

    /**
     * Sets the value of the containedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainedBy }
     *     
     */
    public void setContainedBy(ContainedBy value) {
        this.containedBy = value;
    }

    /**
     * Gets the value of the lineItem property.
     * 
     * @return
     *     possible object is
     *     {@link LineItem }
     *     
     */
    public LineItem getLineItem() {
        return lineItem;
    }

    /**
     * Sets the value of the lineItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineItem }
     *     
     */
    public void setLineItem(LineItem value) {
        this.lineItem = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link Dimensions }
     *     
     */
    public Dimensions getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimensions }
     *     
     */
    public void setDimensions(Dimensions value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the freightClasses property.
     * 
     * @return
     *     possible object is
     *     {@link FreightClasses }
     *     
     */
    public FreightClasses getFreightClasses() {
        return freightClasses;
    }

    /**
     * Sets the value of the freightClasses property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreightClasses }
     *     
     */
    public void setFreightClasses(FreightClasses value) {
        this.freightClasses = value;
    }

    /**
     * Gets the value of the commodity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodity() {
        return commodity;
    }

    /**
     * Sets the value of the commodity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodity(String value) {
        this.commodity = value;
    }

    /**
     * Gets the value of the nmfcCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNmfcCode() {
        return nmfcCode;
    }

    /**
     * Sets the value of the nmfcCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNmfcCode(String value) {
        this.nmfcCode = value;
    }

    /**
     * Gets the value of the stccCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStccCode() {
        return stccCode;
    }

    /**
     * Sets the value of the stccCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStccCode(String value) {
        this.stccCode = value;
    }

    /**
     * Gets the value of the stackability property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStackability() {
        return stackability;
    }

    /**
     * Sets the value of the stackability property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStackability(BigInteger value) {
        this.stackability = value;
    }

    /**
     * Gets the value of the trackingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Sets the value of the trackingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrackingNumber(String value) {
        this.trackingNumber = value;
    }

    /**
     * Gets the value of the deliveryStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * Sets the value of the deliveryStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryStatus(String value) {
        this.deliveryStatus = value;
    }

    /**
     * Gets the value of the minTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinTemperature() {
        return minTemperature;
    }

    /**
     * Sets the value of the minTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinTemperature(String value) {
        this.minTemperature = value;
    }

    /**
     * Gets the value of the maxTemperature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxTemperature() {
        return maxTemperature;
    }

    /**
     * Sets the value of the maxTemperature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxTemperature(String value) {
        this.maxTemperature = value;
    }

    /**
     * Gets the value of the temperatureUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemperatureUnits() {
        return temperatureUnits;
    }

    /**
     * Sets the value of the temperatureUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemperatureUnits(String value) {
        this.temperatureUnits = value;
    }

    /**
     * Gets the value of the hazardousMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHazardousMaterial() {
        return hazardousMaterial;
    }

    /**
     * Sets the value of the hazardousMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHazardousMaterial(String value) {
        this.hazardousMaterial = value;
    }

    /**
     * Gets the value of the hazMatDetail property.
     * 
     * @return
     *     possible object is
     *     {@link HazMatDetail }
     *     
     */
    public HazMatDetail getHazMatDetail() {
        return hazMatDetail;
    }

    /**
     * Sets the value of the hazMatDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link HazMatDetail }
     *     
     */
    public void setHazMatDetail(HazMatDetail value) {
        this.hazMatDetail = value;
    }

    /**
     * Gets the value of the weights property.
     * 
     * @return
     *     possible object is
     *     {@link Weights }
     *     
     */
    public Weights getWeights() {
        return weights;
    }

    /**
     * Sets the value of the weights property.
     * 
     * @param value
     *     allowed object is
     *     {@link Weights }
     *     
     */
    public void setWeights(Weights value) {
        this.weights = value;
    }

    /**
     * Gets the value of the quantities property.
     * 
     * @return
     *     possible object is
     *     {@link Quantities }
     *     
     */
    public Quantities getQuantities() {
        return quantities;
    }

    /**
     * Sets the value of the quantities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quantities }
     *     
     */
    public void setQuantities(Quantities value) {
        this.quantities = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the isShipUnit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsShipUnit() {
        return isShipUnit;
    }

    /**
     * Sets the value of the isShipUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsShipUnit(Boolean value) {
        this.isShipUnit = value;
    }

    /**
     * Gets the value of the isHandlingUnit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsHandlingUnit() {
        return isHandlingUnit;
    }

    /**
     * Sets the value of the isHandlingUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsHandlingUnit(Boolean value) {
        this.isHandlingUnit = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSequence() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSequence(String value) {
        this.sequence = value;
    }

}
