//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.14 at 06:38:41 PM IST 
//


package com.dc.evans.schema.mercurygate;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="AssignedTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Enterprise"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ReferenceNumbers"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Payment"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ItemGroups"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Plan"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}PriceSheets" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Shipments"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Activities" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Notes" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}InternationalDetails" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Comments" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Load")
public class Load {

    @XmlElement(name = "AssignedTo")
    protected String assignedTo;
    @XmlElement(name = "Enterprise", required = true)
    protected Enterprise enterprise;
    @XmlElement(name = "ReferenceNumbers", required = true)
    protected ReferenceNumbers referenceNumbers;
    @XmlElement(name = "Payment", required = true)
    protected Payment payment;
    @XmlElement(name = "ItemGroups", required = true)
    protected ItemGroups itemGroups;
    @XmlElement(name = "Plan", required = true)
    protected Plan plan;
    @XmlElement(name = "PriceSheets")
    protected PriceSheets priceSheets;
    @XmlElement(name = "Shipments", required = true)
    protected Shipments shipments;
    @XmlElement(name = "Activities")
    protected Activities activities;
    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlElement(name = "InternationalDetails")
    protected InternationalDetails internationalDetails;
    @XmlElement(name = "Comments")
    protected Comments comments;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "action")
    protected String action;

    /**
     * Gets the value of the assignedTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssignedTo() {
        return assignedTo;
    }

    /**
     * Sets the value of the assignedTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssignedTo(String value) {
        this.assignedTo = value;
    }

    /**
     * Gets the value of the enterprise property.
     * 
     * @return
     *     possible object is
     *     {@link Enterprise }
     *     
     */
    public Enterprise getEnterprise() {
        return enterprise;
    }

    /**
     * Sets the value of the enterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link Enterprise }
     *     
     */
    public void setEnterprise(Enterprise value) {
        this.enterprise = value;
    }

    /**
     * Gets the value of the referenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumbers }
     *     
     */
    public ReferenceNumbers getReferenceNumbers() {
        return referenceNumbers;
    }

    /**
     * Sets the value of the referenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumbers }
     *     
     */
    public void setReferenceNumbers(ReferenceNumbers value) {
        this.referenceNumbers = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the itemGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ItemGroups }
     *     
     */
    public ItemGroups getItemGroups() {
        return itemGroups;
    }

    /**
     * Sets the value of the itemGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemGroups }
     *     
     */
    public void setItemGroups(ItemGroups value) {
        this.itemGroups = value;
    }

    /**
     * Gets the value of the plan property.
     * 
     * @return
     *     possible object is
     *     {@link Plan }
     *     
     */
    public Plan getPlan() {
        return plan;
    }

    /**
     * Sets the value of the plan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Plan }
     *     
     */
    public void setPlan(Plan value) {
        this.plan = value;
    }

    /**
     * Gets the value of the priceSheets property.
     * 
     * @return
     *     possible object is
     *     {@link PriceSheets }
     *     
     */
    public PriceSheets getPriceSheets() {
        return priceSheets;
    }

    /**
     * Sets the value of the priceSheets property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceSheets }
     *     
     */
    public void setPriceSheets(PriceSheets value) {
        this.priceSheets = value;
    }

    /**
     * Gets the value of the shipments property.
     * 
     * @return
     *     possible object is
     *     {@link Shipments }
     *     
     */
    public Shipments getShipments() {
        return shipments;
    }

    /**
     * Sets the value of the shipments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipments }
     *     
     */
    public void setShipments(Shipments value) {
        this.shipments = value;
    }

    /**
     * Gets the value of the activities property.
     * 
     * @return
     *     possible object is
     *     {@link Activities }
     *     
     */
    public Activities getActivities() {
        return activities;
    }

    /**
     * Sets the value of the activities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Activities }
     *     
     */
    public void setActivities(Activities value) {
        this.activities = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the internationalDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDetails }
     *     
     */
    public InternationalDetails getInternationalDetails() {
        return internationalDetails;
    }

    /**
     * Sets the value of the internationalDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDetails }
     *     
     */
    public void setInternationalDetails(InternationalDetails value) {
        this.internationalDetails = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Comments }
     *     
     */
    public Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments }
     *     
     */
    public void setComments(Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
