//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.14 at 06:38:41 PM IST 
//


package com.dc.evans.schema.mercurygate;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dc.evans.schema.mercurygate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BillTo_QNAME = new QName("urn:MercuryGate:import", "BillTo");
    private final static QName _Status_QNAME = new QName("urn:MercuryGate:import", "Status");
    private final static QName _ContractId_QNAME = new QName("urn:MercuryGate:import", "ContractId");
    private final static QName _SCAC_QNAME = new QName("urn:MercuryGate:import", "SCAC");
    private final static QName _Mode_QNAME = new QName("urn:MercuryGate:import", "Mode");
    private final static QName _Service_QNAME = new QName("urn:MercuryGate:import", "Service");
    private final static QName _AccessorialTotal_QNAME = new QName("urn:MercuryGate:import", "AccessorialTotal");
    private final static QName _SubTotal_QNAME = new QName("urn:MercuryGate:import", "SubTotal");
    private final static QName _Total_QNAME = new QName("urn:MercuryGate:import", "Total");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dc.evans.schema.mercurygate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link LineItem }
     * 
     */
    public LineItem createLineItem() {
        return new LineItem();
    }

    /**
     * Create an instance of {@link PriceSheet }
     * 
     */
    public PriceSheet createPriceSheet() {
        return new PriceSheet();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link Notes.Note }
     * 
     */
    public Notes.Note createNotesNote() {
        return new Notes.Note();
    }

    /**
     * Create an instance of {@link PriceSheet.Carrier }
     * 
     */
    public PriceSheet.Carrier createPriceSheetCarrier() {
        return new PriceSheet.Carrier();
    }

    /**
     * Create an instance of {@link PriceSheet.Carrier.InsuranceTypes }
     * 
     */
    public PriceSheet.Carrier.InsuranceTypes createPriceSheetCarrierInsuranceTypes() {
        return new PriceSheet.Carrier.InsuranceTypes();
    }

    /**
     * Create an instance of {@link ServiceRequest.Data }
     * 
     */
    public ServiceRequest.Data createServiceRequestData() {
        return new ServiceRequest.Data();
    }

    /**
     * Create an instance of {@link ServiceRequest.Data.WebImport }
     * 
     */
    public ServiceRequest.Data.WebImport createServiceRequestDataWebImport() {
        return new ServiceRequest.Data.WebImport();
    }

    /**
     * Create an instance of {@link MercuryGate }
     * 
     */
    public MercuryGate createMercuryGate() {
        return new MercuryGate();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Load }
     * 
     */
    public Load createLoad() {
        return new Load();
    }

    /**
     * Create an instance of {@link Enterprise }
     * 
     */
    public Enterprise createEnterprise() {
        return new Enterprise();
    }

    /**
     * Create an instance of {@link ReferenceNumbers }
     * 
     */
    public ReferenceNumbers createReferenceNumbers() {
        return new ReferenceNumbers();
    }

    /**
     * Create an instance of {@link ReferenceNumber }
     * 
     */
    public ReferenceNumber createReferenceNumber() {
        return new ReferenceNumber();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link TypeLocationEnvelope }
     * 
     */
    public TypeLocationEnvelope createTypeLocationEnvelope() {
        return new TypeLocationEnvelope();
    }

    /**
     * Create an instance of {@link ItemGroups }
     * 
     */
    public ItemGroups createItemGroups() {
        return new ItemGroups();
    }

    /**
     * Create an instance of {@link ItemGroup }
     * 
     */
    public ItemGroup createItemGroup() {
        return new ItemGroup();
    }

    /**
     * Create an instance of {@link MonetaryValue }
     * 
     */
    public MonetaryValue createMonetaryValue() {
        return new MonetaryValue();
    }

    /**
     * Create an instance of {@link ContainedBy }
     * 
     */
    public ContainedBy createContainedBy() {
        return new ContainedBy();
    }

    /**
     * Create an instance of {@link LineItem.Cube }
     * 
     */
    public LineItem.Cube createLineItemCube() {
        return new LineItem.Cube();
    }

    /**
     * Create an instance of {@link Dimensions }
     * 
     */
    public Dimensions createDimensions() {
        return new Dimensions();
    }

    /**
     * Create an instance of {@link Dimension }
     * 
     */
    public Dimension createDimension() {
        return new Dimension();
    }

    /**
     * Create an instance of {@link FreightClasses }
     * 
     */
    public FreightClasses createFreightClasses() {
        return new FreightClasses();
    }

    /**
     * Create an instance of {@link FreightClass }
     * 
     */
    public FreightClass createFreightClass() {
        return new FreightClass();
    }

    /**
     * Create an instance of {@link HazMatDetail }
     * 
     */
    public HazMatDetail createHazMatDetail() {
        return new HazMatDetail();
    }

    /**
     * Create an instance of {@link HazMatFlashPointTemp }
     * 
     */
    public HazMatFlashPointTemp createHazMatFlashPointTemp() {
        return new HazMatFlashPointTemp();
    }

    /**
     * Create an instance of {@link Weights }
     * 
     */
    public Weights createWeights() {
        return new Weights();
    }

    /**
     * Create an instance of {@link Weight }
     * 
     */
    public Weight createWeight() {
        return new Weight();
    }

    /**
     * Create an instance of {@link Quantities }
     * 
     */
    public Quantities createQuantities() {
        return new Quantities();
    }

    /**
     * Create an instance of {@link Quantity }
     * 
     */
    public Quantity createQuantity() {
        return new Quantity();
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link Events }
     * 
     */
    public Events createEvents() {
        return new Events();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Dates }
     * 
     */
    public Dates createDates() {
        return new Dates();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Pickup }
     * 
     */
    public Pickup createPickup() {
        return new Pickup();
    }

    /**
     * Create an instance of {@link Drop }
     * 
     */
    public Drop createDrop() {
        return new Drop();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link AppointmentTime }
     * 
     */
    public AppointmentTime createAppointmentTime() {
        return new AppointmentTime();
    }

    /**
     * Create an instance of {@link Contacts }
     * 
     */
    public Contacts createContacts() {
        return new Contacts();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link ContactMethods }
     * 
     */
    public ContactMethods createContactMethods() {
        return new ContactMethods();
    }

    /**
     * Create an instance of {@link ContactMethod }
     * 
     */
    public ContactMethod createContactMethod() {
        return new ContactMethod();
    }

    /**
     * Create an instance of {@link Shipments }
     * 
     */
    public Shipments createShipments() {
        return new Shipments();
    }

    /**
     * Create an instance of {@link Shipment }
     * 
     */
    public Shipment createShipment() {
        return new Shipment();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link com.dc.evans.schema.mercurygate.Comment }
     * 
     */
    public com.dc.evans.schema.mercurygate.Comment createComment() {
        return new com.dc.evans.schema.mercurygate.Comment();
    }

    /**
     * Create an instance of {@link EquipmentList }
     * 
     */
    public EquipmentList createEquipmentList() {
        return new EquipmentList();
    }

    /**
     * Create an instance of {@link ServiceList }
     * 
     */
    public ServiceList createServiceList() {
        return new ServiceList();
    }

    /**
     * Create an instance of {@link Shipper }
     * 
     */
    public Shipper createShipper() {
        return new Shipper();
    }

    /**
     * Create an instance of {@link Consignee }
     * 
     */
    public Consignee createConsignee() {
        return new Consignee();
    }

    /**
     * Create an instance of {@link PriceSheets }
     * 
     */
    public PriceSheets createPriceSheets() {
        return new PriceSheets();
    }

    /**
     * Create an instance of {@link NormalizedTotal }
     * 
     */
    public NormalizedTotal createNormalizedTotal() {
        return new NormalizedTotal();
    }

    /**
     * Create an instance of {@link Charges }
     * 
     */
    public Charges createCharges() {
        return new Charges();
    }

    /**
     * Create an instance of {@link Charge }
     * 
     */
    public Charge createCharge() {
        return new Charge();
    }

    /**
     * Create an instance of {@link Activities }
     * 
     */
    public Activities createActivities() {
        return new Activities();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link InternationalDetails }
     * 
     */
    public InternationalDetails createInternationalDetails() {
        return new InternationalDetails();
    }

    /**
     * Create an instance of {@link LetterOfCredit }
     * 
     */
    public LetterOfCredit createLetterOfCredit() {
        return new LetterOfCredit();
    }

    /**
     * Create an instance of {@link GenericField }
     * 
     */
    public GenericField createGenericField() {
        return new GenericField();
    }

    /**
     * Create an instance of {@link TypeDates }
     * 
     */
    public TypeDates createTypeDates() {
        return new TypeDates();
    }

    /**
     * Create an instance of {@link Notes.Note.Comment }
     * 
     */
    public Notes.Note.Comment createNotesNoteComment() {
        return new Notes.Note.Comment();
    }

    /**
     * Create an instance of {@link PriceSheet.Carrier.InsuranceTypes.Insurance }
     * 
     */
    public PriceSheet.Carrier.InsuranceTypes.Insurance createPriceSheetCarrierInsuranceTypesInsurance() {
        return new PriceSheet.Carrier.InsuranceTypes.Insurance();
    }

    /**
     * Create an instance of {@link ServiceRequest.Data.WebImport.WebImportHeader }
     * 
     */
    public ServiceRequest.Data.WebImport.WebImportHeader createServiceRequestDataWebImportWebImportHeader() {
        return new ServiceRequest.Data.WebImport.WebImportHeader();
    }

    /**
     * Create an instance of {@link ServiceRequest.Data.WebImport.WebImportFile }
     * 
     */
    public ServiceRequest.Data.WebImport.WebImportFile createServiceRequestDataWebImportWebImportFile() {
        return new ServiceRequest.Data.WebImport.WebImportFile();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeLocationEnvelope }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TypeLocationEnvelope }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "BillTo")
    public JAXBElement<TypeLocationEnvelope> createBillTo(TypeLocationEnvelope value) {
        return new JAXBElement<TypeLocationEnvelope>(_BillTo_QNAME, TypeLocationEnvelope.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "Status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "ContractId")
    public JAXBElement<String> createContractId(String value) {
        return new JAXBElement<String>(_ContractId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "SCAC")
    public JAXBElement<String> createSCAC(String value) {
        return new JAXBElement<String>(_SCAC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "Mode")
    public JAXBElement<String> createMode(String value) {
        return new JAXBElement<String>(_Mode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "Service")
    public JAXBElement<String> createService(String value) {
        return new JAXBElement<String>(_Service_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "AccessorialTotal")
    public JAXBElement<String> createAccessorialTotal(String value) {
        return new JAXBElement<String>(_AccessorialTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "SubTotal")
    public JAXBElement<String> createSubTotal(String value) {
        return new JAXBElement<String>(_SubTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "urn:MercuryGate:import", name = "Total")
    public JAXBElement<String> createTotal(String value) {
        return new JAXBElement<String>(_Total_QNAME, String.class, null, value);
    }

}
