//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.14 at 06:38:41 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "urn:MercuryGate:import", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dc.evans.schema.mercurygate;
