//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.20 at 03:28:09 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.dc.evans.schema.mercurygate;
