//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.14 at 06:38:41 PM IST 
//


package com.dc.evans.schema.mercurygate;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ContractId" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}SCAC" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Mode" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Service" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}AccessorialTotal" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}SubTotal" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Total" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}NormalizedTotal" minOccurs="0"/&gt;
 *         &lt;element name="Carrier"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="CarrierId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="CarrierName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="SCAC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Mode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Service" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="ServiceDays" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="InsuranceTypes"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="Insurance" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *                                     &lt;attribute name="company" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="contactName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                     &lt;attribute name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Charges" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="type" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="Carrier"/&gt;
 *             &lt;enumeration value="Customer"/&gt;
 *             &lt;enumeration value="Charge"/&gt;
 *             &lt;enumeration value="Cost"/&gt;
 *             &lt;enumeration value="Billed"/&gt;
 *             &lt;enumeration value="VendorRate"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="isSelected" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="updateDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="currencyCode" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="exchangeDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "PriceSheet")
public class PriceSheet {

    @XmlElement(name = "ContractId")
    protected String contractId;
    @XmlElement(name = "SCAC")
    protected String scac;
    @XmlElement(name = "Mode")
    protected String mode;
    @XmlElement(name = "Service")
    protected String service;
    @XmlElement(name = "AccessorialTotal")
    protected String accessorialTotal;
    @XmlElement(name = "SubTotal")
    protected String subTotal;
    @XmlElement(name = "Total")
    protected String total;
    @XmlElement(name = "NormalizedTotal")
    protected NormalizedTotal normalizedTotal;
    @XmlElement(name = "Carrier", required = true)
    protected PriceSheet.Carrier carrier;
    @XmlElement(name = "Charges")
    protected Charges charges;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "isSelected", required = true)
    protected String isSelected;
    @XmlAttribute(name = "updateDate")
    protected String updateDate;
    @XmlAttribute(name = "currencyCode")
    protected String currencyCode;
    @XmlAttribute(name = "exchangeDate")
    protected String exchangeDate;

    /**
     * Gets the value of the contractId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * Sets the value of the contractId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractId(String value) {
        this.contractId = value;
    }

    /**
     * Gets the value of the scac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCAC() {
        return scac;
    }

    /**
     * Sets the value of the scac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCAC(String value) {
        this.scac = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the accessorialTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessorialTotal() {
        return accessorialTotal;
    }

    /**
     * Sets the value of the accessorialTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessorialTotal(String value) {
        this.accessorialTotal = value;
    }

    /**
     * Gets the value of the subTotal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubTotal() {
        return subTotal;
    }

    /**
     * Sets the value of the subTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubTotal(String value) {
        this.subTotal = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotal(String value) {
        this.total = value;
    }

    /**
     * Gets the value of the normalizedTotal property.
     * 
     * @return
     *     possible object is
     *     {@link NormalizedTotal }
     *     
     */
    public NormalizedTotal getNormalizedTotal() {
        return normalizedTotal;
    }

    /**
     * Sets the value of the normalizedTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link NormalizedTotal }
     *     
     */
    public void setNormalizedTotal(NormalizedTotal value) {
        this.normalizedTotal = value;
    }

    /**
     * Gets the value of the carrier property.
     * 
     * @return
     *     possible object is
     *     {@link PriceSheet.Carrier }
     *     
     */
    public PriceSheet.Carrier getCarrier() {
        return carrier;
    }

    /**
     * Sets the value of the carrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceSheet.Carrier }
     *     
     */
    public void setCarrier(PriceSheet.Carrier value) {
        this.carrier = value;
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link Charges }
     *     
     */
    public Charges getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Charges }
     *     
     */
    public void setCharges(Charges value) {
        this.charges = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the isSelected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsSelected() {
        return isSelected;
    }

    /**
     * Sets the value of the isSelected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsSelected(String value) {
        this.isSelected = value;
    }

    /**
     * Gets the value of the updateDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUpdateDate() {
        return updateDate;
    }

    /**
     * Sets the value of the updateDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateDate(String value) {
        this.updateDate = value;
    }

    /**
     * Gets the value of the currencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * Sets the value of the currencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrencyCode(String value) {
        this.currencyCode = value;
    }

    /**
     * Gets the value of the exchangeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeDate() {
        return exchangeDate;
    }

    /**
     * Sets the value of the exchangeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeDate(String value) {
        this.exchangeDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="CarrierId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="CarrierName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="SCAC" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Mode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Service" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="ServiceDays" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="Distance" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="InsuranceTypes"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="Insurance" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
     *                           &lt;attribute name="company" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="contactName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                           &lt;attribute name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "carrierId",
        "carrierName",
        "scac",
        "mode",
        "service",
        "serviceDays",
        "distance",
        "id",
        "insuranceTypes"
    })
    public static class Carrier {

        @XmlElement(name = "CarrierId", required = true)
        protected String carrierId;
        @XmlElement(name = "CarrierName", required = true)
        protected String carrierName;
        @XmlElement(name = "SCAC", required = true)
        protected String scac;
        @XmlElement(name = "Mode", required = true)
        protected String mode;
        @XmlElement(name = "Service", required = true)
        protected String service;
        @XmlElement(name = "ServiceDays", required = true)
        protected BigDecimal serviceDays;
        @XmlElement(name = "Distance", required = true)
        protected BigDecimal distance;
        @XmlElement(name = "Id", required = true)
        protected String id;
        @XmlElement(name = "InsuranceTypes", required = true)
        protected PriceSheet.Carrier.InsuranceTypes insuranceTypes;

        /**
         * Gets the value of the carrierId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCarrierId() {
            return carrierId;
        }

        /**
         * Sets the value of the carrierId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCarrierId(String value) {
            this.carrierId = value;
        }

        /**
         * Gets the value of the carrierName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCarrierName() {
            return carrierName;
        }

        /**
         * Sets the value of the carrierName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCarrierName(String value) {
            this.carrierName = value;
        }

        /**
         * Gets the value of the scac property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSCAC() {
            return scac;
        }

        /**
         * Sets the value of the scac property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSCAC(String value) {
            this.scac = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMode(String value) {
            this.mode = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setService(String value) {
            this.service = value;
        }

        /**
         * Gets the value of the serviceDays property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getServiceDays() {
            return serviceDays;
        }

        /**
         * Sets the value of the serviceDays property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setServiceDays(BigDecimal value) {
            this.serviceDays = value;
        }

        /**
         * Gets the value of the distance property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDistance() {
            return distance;
        }

        /**
         * Sets the value of the distance property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDistance(BigDecimal value) {
            this.distance = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the insuranceTypes property.
         * 
         * @return
         *     possible object is
         *     {@link PriceSheet.Carrier.InsuranceTypes }
         *     
         */
        public PriceSheet.Carrier.InsuranceTypes getInsuranceTypes() {
            return insuranceTypes;
        }

        /**
         * Sets the value of the insuranceTypes property.
         * 
         * @param value
         *     allowed object is
         *     {@link PriceSheet.Carrier.InsuranceTypes }
         *     
         */
        public void setInsuranceTypes(PriceSheet.Carrier.InsuranceTypes value) {
            this.insuranceTypes = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="Insurance" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
         *                 &lt;attribute name="company" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="contactName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                 &lt;attribute name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "insurance"
        })
        public static class InsuranceTypes {

            @XmlElement(name = "Insurance", required = true)
            protected List<PriceSheet.Carrier.InsuranceTypes.Insurance> insurance;

            /**
             * Gets the value of the insurance property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the insurance property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getInsurance().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PriceSheet.Carrier.InsuranceTypes.Insurance }
             * 
             * 
             */
            public List<PriceSheet.Carrier.InsuranceTypes.Insurance> getInsurance() {
                if (insurance == null) {
                    insurance = new ArrayList<PriceSheet.Carrier.InsuranceTypes.Insurance>();
                }
                return this.insurance;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="amount" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
             *       &lt;attribute name="company" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="contactName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *       &lt;attribute name="contactPhone" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Insurance {

                @XmlAttribute(name = "type", required = true)
                protected String type;
                @XmlAttribute(name = "amount", required = true)
                protected BigDecimal amount;
                @XmlAttribute(name = "company")
                protected String company;
                @XmlAttribute(name = "expirationDate")
                protected String expirationDate;
                @XmlAttribute(name = "contactName")
                protected String contactName;
                @XmlAttribute(name = "contactPhone")
                protected String contactPhone;

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the amount property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getAmount() {
                    return amount;
                }

                /**
                 * Sets the value of the amount property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setAmount(BigDecimal value) {
                    this.amount = value;
                }

                /**
                 * Gets the value of the company property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCompany() {
                    return company;
                }

                /**
                 * Sets the value of the company property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCompany(String value) {
                    this.company = value;
                }

                /**
                 * Gets the value of the expirationDate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getExpirationDate() {
                    return expirationDate;
                }

                /**
                 * Sets the value of the expirationDate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setExpirationDate(String value) {
                    this.expirationDate = value;
                }

                /**
                 * Gets the value of the contactName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContactName() {
                    return contactName;
                }

                /**
                 * Sets the value of the contactName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContactName(String value) {
                    this.contactName = value;
                }

                /**
                 * Gets the value of the contactPhone property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContactPhone() {
                    return contactPhone;
                }

                /**
                 * Sets the value of the contactPhone property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContactPhone(String value) {
                    this.contactPhone = value;
                }

            }

        }

    }

}
