//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.20 at 03:28:09 PM IST 
//


package com.dc.evans.schema.mercurygate;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="service-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="request-id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="WebImport"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="WebImportHeader"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="WebImportFile"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element ref="{urn:MercuryGate:import}MercuryGate"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceId",
    "requestId",
    "data"
})
@XmlRootElement(name = "service-request")
public class ServiceRequest {

    @XmlElement(name = "service-id", required = true)
    protected String serviceId;
    @XmlElement(name = "request-id", required = true)
    protected String requestId;
    @XmlElement(required = true)
    protected ServiceRequest.Data data;

    /**
     * Gets the value of the serviceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceId() {
        return serviceId;
    }

    /**
     * Sets the value of the serviceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceId(String value) {
        this.serviceId = value;
    }

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceRequest.Data }
     *     
     */
    public ServiceRequest.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceRequest.Data }
     *     
     */
    public void setData(ServiceRequest.Data value) {
        this.data = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="WebImport"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="WebImportHeader"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="WebImportFile"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element ref="{urn:MercuryGate:import}MercuryGate"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "webImport"
    })
    public static class Data {

        @XmlElement(name = "WebImport", required = true)
        protected ServiceRequest.Data.WebImport webImport;

        /**
         * Gets the value of the webImport property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceRequest.Data.WebImport }
         *     
         */
        public ServiceRequest.Data.WebImport getWebImport() {
            return webImport;
        }

        /**
         * Sets the value of the webImport property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceRequest.Data.WebImport }
         *     
         */
        public void setWebImport(ServiceRequest.Data.WebImport value) {
            this.webImport = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="WebImportHeader"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="WebImportFile"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element ref="{urn:MercuryGate:import}MercuryGate"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "webImportHeader",
            "webImportFile"
        })
        public static class WebImport {

            @XmlElement(name = "WebImportHeader", required = true)
            protected ServiceRequest.Data.WebImport.WebImportHeader webImportHeader;
            @XmlElement(name = "WebImportFile", required = true)
            protected ServiceRequest.Data.WebImport.WebImportFile webImportFile;

            /**
             * Gets the value of the webImportHeader property.
             * 
             * @return
             *     possible object is
             *     {@link ServiceRequest.Data.WebImport.WebImportHeader }
             *     
             */
            public ServiceRequest.Data.WebImport.WebImportHeader getWebImportHeader() {
                return webImportHeader;
            }

            /**
             * Sets the value of the webImportHeader property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServiceRequest.Data.WebImport.WebImportHeader }
             *     
             */
            public void setWebImportHeader(ServiceRequest.Data.WebImport.WebImportHeader value) {
                this.webImportHeader = value;
            }

            /**
             * Gets the value of the webImportFile property.
             * 
             * @return
             *     possible object is
             *     {@link ServiceRequest.Data.WebImport.WebImportFile }
             *     
             */
            public ServiceRequest.Data.WebImport.WebImportFile getWebImportFile() {
                return webImportFile;
            }

            /**
             * Sets the value of the webImportFile property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServiceRequest.Data.WebImport.WebImportFile }
             *     
             */
            public void setWebImportFile(ServiceRequest.Data.WebImport.WebImportFile value) {
                this.webImportFile = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element ref="{urn:MercuryGate:import}MercuryGate"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "mercuryGate"
            })
            public static class WebImportFile {

                @XmlElement(name = "MercuryGate", required = true)
                protected MercuryGate mercuryGate;

                /**
                 * Gets the value of the mercuryGate property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MercuryGate }
                 *     
                 */
                public MercuryGate getMercuryGate() {
                    return mercuryGate;
                }

                /**
                 * Sets the value of the mercuryGate property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MercuryGate }
                 *     
                 */
                public void setMercuryGate(MercuryGate value) {
                    this.mercuryGate = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="Type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="UserName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "fileName",
                "type",
                "userName"
            })
            public static class WebImportHeader {

                @XmlElement(name = "FileName", required = true)
                protected String fileName;
                @XmlElement(name = "Type", required = true)
                protected String type;
                @XmlElement(name = "UserName", required = true)
                protected String userName;

                /**
                 * Gets the value of the fileName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFileName() {
                    return fileName;
                }

                /**
                 * Sets the value of the fileName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFileName(String value) {
                    this.fileName = value;
                }

                /**
                 * Gets the value of the type property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getType() {
                    return type;
                }

                /**
                 * Sets the value of the type property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setType(String value) {
                    this.type = value;
                }

                /**
                 * Gets the value of the userName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUserName() {
                    return userName;
                }

                /**
                 * Sets the value of the userName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUserName(String value) {
                    this.userName = value;
                }

            }

        }

    }

}
