//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.14 at 06:38:41 PM IST 
//


package com.dc.evans.schema.mercurygate;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{urn:MercuryGate:import}ReferenceNumbers" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element ref="{urn:MercuryGate:import}Shipment" maxOccurs="unbounded"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "referenceNumbers",
    "shipment"
})
@XmlRootElement(name = "Shipments")
public class Shipments {

    @XmlElement(name = "ReferenceNumbers")
    protected ReferenceNumbers referenceNumbers;
    @XmlElement(name = "Shipment")
    protected List<Shipment> shipment;

    /**
     * Gets the value of the referenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumbers }
     *     
     */
    public ReferenceNumbers getReferenceNumbers() {
        return referenceNumbers;
    }

    /**
     * Sets the value of the referenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumbers }
     *     
     */
    public void setReferenceNumbers(ReferenceNumbers value) {
        this.referenceNumbers = value;
    }

    /**
     * Gets the value of the shipment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the shipment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Shipment }
     * 
     * 
     */
    public List<Shipment> getShipment() {
        if (shipment == null) {
            shipment = new ArrayList<Shipment>();
        }
        return this.shipment;
    }

}
