//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.08.20 at 03:28:09 PM IST 
//


package com.dc.evans.schema.mercurygate;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Status" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Enterprise" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ReferenceNumbers"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Comments" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Dimensions"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}EquipmentList" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ServiceList" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Dates"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Shipper"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Consignee"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}ItemGroups"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Payment"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}PriceSheets" minOccurs="0"/&gt;
 *         &lt;element ref="{urn:MercuryGate:import}Notes" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="action" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Shipment")
public class Shipment {

    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "Enterprise")
    protected Enterprise enterprise;
    @XmlElement(name = "ReferenceNumbers", required = true)
    protected ReferenceNumbers referenceNumbers;
    @XmlElement(name = "Comments")
    protected Comments comments;
    @XmlElement(name = "Dimensions", required = true)
    protected Dimensions dimensions;
    @XmlElement(name = "EquipmentList")
    protected EquipmentList equipmentList;
    @XmlElement(name = "ServiceList")
    protected ServiceList serviceList;
    @XmlElement(name = "Dates", required = true)
    protected Dates dates;
    @XmlElement(name = "Shipper", required = true)
    protected Shipper shipper;
    @XmlElement(name = "Consignee", required = true)
    protected Consignee consignee;
    @XmlElement(name = "ItemGroups", required = true)
    protected ItemGroups itemGroups;
    @XmlElement(name = "Payment", required = true)
    protected Payment payment;
    @XmlElement(name = "PriceSheets")
    protected PriceSheets priceSheets;
    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "action")
    protected String action;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the enterprise property.
     * 
     * @return
     *     possible object is
     *     {@link Enterprise }
     *     
     */
    public Enterprise getEnterprise() {
        return enterprise;
    }

    /**
     * Sets the value of the enterprise property.
     * 
     * @param value
     *     allowed object is
     *     {@link Enterprise }
     *     
     */
    public void setEnterprise(Enterprise value) {
        this.enterprise = value;
    }

    /**
     * Gets the value of the referenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumbers }
     *     
     */
    public ReferenceNumbers getReferenceNumbers() {
        return referenceNumbers;
    }

    /**
     * Sets the value of the referenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumbers }
     *     
     */
    public void setReferenceNumbers(ReferenceNumbers value) {
        this.referenceNumbers = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link Comments }
     *     
     */
    public Comments getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comments }
     *     
     */
    public void setComments(Comments value) {
        this.comments = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link Dimensions }
     *     
     */
    public Dimensions getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimensions }
     *     
     */
    public void setDimensions(Dimensions value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the equipmentList property.
     * 
     * @return
     *     possible object is
     *     {@link EquipmentList }
     *     
     */
    public EquipmentList getEquipmentList() {
        return equipmentList;
    }

    /**
     * Sets the value of the equipmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentList }
     *     
     */
    public void setEquipmentList(EquipmentList value) {
        this.equipmentList = value;
    }

    /**
     * Gets the value of the serviceList property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceList }
     *     
     */
    public ServiceList getServiceList() {
        return serviceList;
    }

    /**
     * Sets the value of the serviceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceList }
     *     
     */
    public void setServiceList(ServiceList value) {
        this.serviceList = value;
    }

    /**
     * Gets the value of the dates property.
     * 
     * @return
     *     possible object is
     *     {@link Dates }
     *     
     */
    public Dates getDates() {
        return dates;
    }

    /**
     * Sets the value of the dates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dates }
     *     
     */
    public void setDates(Dates value) {
        this.dates = value;
    }

    /**
     * Gets the value of the shipper property.
     * 
     * @return
     *     possible object is
     *     {@link Shipper }
     *     
     */
    public Shipper getShipper() {
        return shipper;
    }

    /**
     * Sets the value of the shipper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Shipper }
     *     
     */
    public void setShipper(Shipper value) {
        this.shipper = value;
    }

    /**
     * Gets the value of the consignee property.
     * 
     * @return
     *     possible object is
     *     {@link Consignee }
     *     
     */
    public Consignee getConsignee() {
        return consignee;
    }

    /**
     * Sets the value of the consignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Consignee }
     *     
     */
    public void setConsignee(Consignee value) {
        this.consignee = value;
    }

    /**
     * Gets the value of the itemGroups property.
     * 
     * @return
     *     possible object is
     *     {@link ItemGroups }
     *     
     */
    public ItemGroups getItemGroups() {
        return itemGroups;
    }

    /**
     * Sets the value of the itemGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemGroups }
     *     
     */
    public void setItemGroups(ItemGroups value) {
        this.itemGroups = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the priceSheets property.
     * 
     * @return
     *     possible object is
     *     {@link PriceSheets }
     *     
     */
    public PriceSheets getPriceSheets() {
        return priceSheets;
    }

    /**
     * Sets the value of the priceSheets property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriceSheets }
     *     
     */
    public void setPriceSheets(PriceSheets value) {
        this.priceSheets = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

}
